# Generated by Django 5.1.5 on 2025-09-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tipo_publicacion',
            field=models.CharField(blank=True, choices=[('departamento', 'Departamentos'), ('oficina', 'Oficinas'), ('salon', 'Salones')], max_length=20, null=True),
        ),
    ]
