# Generated by Django 5.1.5 on 2025-09-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='baneado',
            field=models.BooleanField(default=False),
        ),
    ]
