# Generated by Django 5.1.5 on 2025-09-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuariopersonalizado_baneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='apellido',
            field=models.CharField(default='N/A', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='ciudad',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='direccion',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='dni',
            field=models.CharField(default='N/A', max_length=30, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nacimiento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='num_calle',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(max_length=254, unique=True, blank=True, null=True),
        ),
    ]
