# Generated by Django 5.1.5 on 2025-09-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuariopersonalizado_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='dni',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
