# Generated by Django 5.1.5 on 2025-09-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuariopersonalizado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(default='N/A', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
