# Generated by Django 5.1.5 on 2025-09-18 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuariopersonalizado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='num_calle',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El número no puede ser menor a 0.'), django.core.validators.MaxValueValidator(10000, message='El número no puede ser mayor a 10.000')]),
        ),
    ]
