# Generated by Django 5.1.5 on 2025-09-25 23:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuariopersonalizado_num_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_publicacion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('departamento', 'Departamentos'), ('oficina', 'Oficinas'), ('salon', 'Salones')], default=[], max_length=26),
            preserve_default=False,
        ),
    ]
