# Generated by Django 5.1.5 on 2025-09-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuariopersonalizado_tipo_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(default=3416994676, max_length=30),
            preserve_default=False,
        ),
    ]
