# Generated by Django 5.1.5 on 2025-09-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuariopersonalizado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='usuarios.comentario'),
        ),
    ]
