# Generated by Django 5.1.5 on 2025-10-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_comentario_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='ciudad',
        ),
    ]
