# Generated by Django 5.1.5 on 2025-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_usuariopersonalizado_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
