# Generated by Django 5.1.5 on 2025-11-07 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_usuariopersonalizado_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='num_calle',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='El número no puede ser menor a 0.'), django.core.validators.MaxValueValidator(10000, message='El número no puede ser mayor a 10.000')]),
        ),
    ]
