# Generated by Django 5.1.5 on 2025-11-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_usuariopersonalizado_num_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
