# Generated by Django 5.1.5 on 2025-11-16 18:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_usuariopersonalizado_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='avatar',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
