# Generated by Django 5.1.5 on 2025-11-16 19:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_remove_usuariopersonalizado_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatars/default_avatar.png', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
