# Generated by Django 5.1.5 on 2025-07-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0002_salones_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='salones/'),
        ),
    ]
