# Generated by Django 5.1.5 on 2025-09-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0003_alter_salones_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='salones',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
