# Generated by Django 5.1.5 on 2025-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0005_salones_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='salones',
            name='monedas',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares (USD)')], default='ARS', max_length=3),
        ),
    ]
