# Generated by Django 5.1.5 on 2025-10-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0006_salones_monedas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salones',
            old_name='ubicacion',
            new_name='direccion',
        ),
    ]
