# Generated by Django 5.1.5 on 2025-11-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0010_alter_salones_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='salones',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salones',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
