# Generated by Django 5.1.5 on 2025-11-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0012_alter_salones_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salones',
            name='zona',
            field=models.CharField(blank=True, choices=[('Centro', 'Centro'), ('Macrocentro', 'Macrocentro'), ('Echesortu', 'Echesortu'), ('Abasto', 'Abasto'), ('Tablada', 'Tablada'), ('Martin', 'Martin'), ('Las Delicias', 'Las Delicias'), ('Fisherton', 'Fisherton'), ('Arroyito', 'Arroyito'), ('Pichincha', 'Pichincha'), ('Luis Agote', 'Luis Agote'), ('Alberdi', 'Alberdi'), ('Empalme Graneros', 'Empalme Graneros'), ('Ludueña', 'Ludueña'), ('Belgrano', 'Belgrano'), ('Azcuénaga', 'Azcuénaga'), ('Refinería', 'Refinería'), ('Hospitales', 'Hospitales'), ('La Florida', 'La Florida'), ('Sarmiento', 'Sarmiento'), ('Hostal del Sol', 'Hostal del Sol'), ('Barrio Rucci', 'Barrio Rucci'), ('Godoy', 'Godoy'), ('7 de Septiembre', '7 de Septiembre'), ('Lisandro de la Torre', 'Lisandro de la Torre'), ('Antártida Argentina', 'Antártida Argentina'), ('Lomas de Alberdi', 'Lomas de Alberdi'), ('Zona Norte', 'Norte'), ('Zona Oeste', 'Oeste'), ('Zona Este', 'Este'), ('Zona Sur', 'Sur'), ('Zona Suroeste', 'Suroeste'), ('Zona Sudeste', 'Sudeste'), ('Villa Gobernador Gálvez', 'Villa Gobernador Gálvez'), ('Granadero Baigorria', 'Granadero Baigorria'), ('San Lorenzo', 'San Lorenzo'), ('Fray Luis Beltrán', 'Fray Luis Beltrán'), ('Ricardone', 'Ricardone'), ('Funes', 'Funes'), ('Roldán', 'Roldán'), ('Soldini', 'Soldini'), ('Perez', 'Pérez'), ('Puente Gallego', 'Puente Gallego'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
