# Generated by Django 5.1.5 on 2025-11-16 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0014_alter_salones_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensalon',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='salones',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
