# Generated by Django 5.1.5 on 2025-11-16 18:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0015_alter_imagensalon_imagen_alter_salones_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensalon',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='salones',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
