# Generated by Django 5.1.5 on 2025-08-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenoficina',
            name='imagen',
            field=models.ImageField(blank=True, default='oficinas/imagenes/default.jpg', upload_to='oficinas/imagenes/'),
        ),
    ]
