# Generated by Django 5.1.5 on 2025-09-02 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0002_alter_imagenoficina_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagenoficina',
            name='imagen',
            field=models.ImageField(blank=True, default='media/oficinas/imagenes/default.jpg', upload_to='oficinas/imagenes/'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='ambientes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Debe tener al menos 1 ambiente'), django.core.validators.MaxValueValidator(20, message='Seleccione una cantidad correcta')]),
        ),
    ]
