# Generated by Django 5.1.5 on 2025-09-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0004_oficina_propietario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oficina',
            old_name='ubicacion',
            new_name='direccion',
        ),
    ]
