# Generated by Django 5.1.5 on 2025-09-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0005_rename_ubicacion_oficina_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='monedas',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares (USD)')], default='ARS', max_length=3),
        ),
    ]
