# Generated by Django 5.1.5 on 2025-09-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0006_oficina_monedas'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='departamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oficina',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
