# Generated by Django 5.1.5 on 2025-09-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0007_oficina_departamento_oficina_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='departamento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
