# Generated by Django 5.1.5 on 2025-09-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0008_alter_oficina_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oficina',
            old_name='direccion',
            new_name='ubicacion',
        ),
    ]
