# Generated by Django 5.1.5 on 2025-09-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0009_rename_direccion_oficina_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oficina',
            old_name='ubicacion',
            new_name='direccion',
        ),
    ]
