# Generated by Django 5.1.5 on 2025-10-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0010_rename_ubicacion_oficina_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficina',
            name='nombre',
        ),
    ]
