# Generated by Django 5.1.5 on 2025-10-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0012_oficina_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='zona',
            field=models.CharField(blank=True, choices=[('Centro', 'Centro'), ('Macrocentro', 'Macrocentro'), ('Echesortu', 'Echesortu'), ('Abasto', 'Abasto'), ('Tablada', 'Tablada'), ('Las Delicias', 'Las Delicias'), ('Fisherton', 'Fisherton'), ('Arroyito', 'Arroyito'), ('Pichincha', 'Pichincha'), ('Zona Norte', 'Norte'), ('Zona Oeste', 'Oeste'), ('Zona Este', 'Este'), ('Zona Sur', 'Sur'), ('Zona Suroeste', 'Suroeste'), ('Zona Sudeste', 'Sudeste'), ('Villa Gobernador Gálvez', 'Villa Gobernador Gálvez'), ('Granadero Baigorria', 'Granadero Baigorria'), ('Ricardone', 'Ricardone'), ('San Lorenzo', 'San Lorenzo'), ('Fray Luis Beltrán', 'Fray Luis Beltrán'), ('Funes', 'Funes'), ('Roldan', 'Roldán'), ('Soldini', 'Soldini'), ('Perez', 'Pérez'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
