# Generated by Django 5.1.5 on 2025-11-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0013_alter_oficina_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oficina',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
