# Generated by Django 5.1.5 on 2025-11-16 16:07

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0016_alter_oficina_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenoficina',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
