# Generated by Django 5.1.5 on 2025-11-16 18:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas', '0017_oficina_imagen_alter_imagenoficina_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenoficina',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
