# Generated by Django 5.1.5 on 2025-05-13 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={},
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='departamentos/imagenes')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='departamentos.departamentos')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
