# Generated by Django 5.1.5 on 2025-05-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamentos_options_imagendepartamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='imagendepartamento',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
    ]
