# Generated by Django 5.1.5 on 2025-07-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_departamentos_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='zona',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
