# Generated by Django 5.1.5 on 2025-09-02 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0005_departamentos_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='banos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Debe tener al menos 1 baño'), django.core.validators.MaxValueValidator(8, message='Seleccione una cantidad correcta')]),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='habitaciones',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Debe tener al menos 1 habitación'), django.core.validators.MaxValueValidator(20, message='Seleccione una cantidad correcta')]),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El nombre no puede estar vacío', 'null': 'El nombre no puede ser nulo'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='piso',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Seleccione un piso correcto'), django.core.validators.MaxValueValidator(20, message='Seleccione un piso correcto')]),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='zona',
            field=models.CharField(blank=True, choices=[('centro', 'Centro'), ('macrocentro', 'Macrocentro'), ('echesortu', 'Echesortu'), ('abasto', 'Abasto'), ('tablada', 'Tablada'), ('las_delicias', 'Las Delicias'), ('fisherton', 'Fisherton'), ('arroyito', 'Arroyito'), ('aladelta', 'Alto Rosario'), ('pichincha', 'Pichincha'), ('zona_norte', 'Zona Norte'), ('zona_oeste', 'Zona Oeste'), ('zona_este', 'Zona Este'), ('zona_sur', 'Zona Sur'), ('zona_suroeste', 'Zona Suroeste'), ('zona_sudeste', 'Zona Sudeste'), ('villa_gobernador_galvez', 'Villa Gobernador Gálvez'), ('granadero_baigorria', 'Granadero Baigorria'), ('ricardone', 'Ricardone'), ('san_lorenzo', 'San Lorenzo'), ('fray_luis_beltran', 'Fray Luis Beltrán'), ('funes', 'Funes'), ('roldan', 'Roldán'), ('soldini', 'Soldini'), ('perez', 'Pérez'), ('other', 'Otro')], max_length=50, null=True),
        ),
    ]
