# Generated by Django 5.1.5 on 2025-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_departamentos_aprobado_alter_departamentos_banos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='monedas',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares (USD)')], default='ARS', max_length=3),
        ),
    ]
