# Generated by Django 5.1.5 on 2025-09-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0007_departamentos_monedas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='departamento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
