# Generated by Django 5.1.5 on 2025-10-01 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0009_departamentos_latitud_departamentos_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='habitaciones',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Inserte un valor valido'), django.core.validators.MaxValueValidator(20, message='Seleccione una cantidad correcta')]),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(blank=True, error_messages={'blank': 'El nombre no puede estar vacío', 'null': 'El nombre no puede ser nulo'}, max_length=100, null=True),
        ),
    ]
