# Generated by Django 5.1.5 on 2025-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0010_alter_departamentos_habitaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
    ]
