# Generated by Django 5.1.5 on 2025-10-01 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0011_alter_departamentos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
