# Generated by Django 5.1.5 on 2025-10-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0012_alter_departamentos_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='departamentos',
            name='longitud',
        ),
    ]
