# Generated by Django 5.1.5 on 2025-10-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0013_remove_departamentos_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='zona',
            field=models.CharField(blank=True, choices=[('Centro', 'Centro'), ('Macrocentro', 'Macrocentro'), ('Echesortu', 'Echesortu'), ('Abasto', 'Abasto'), ('Tablada', 'Tablada'), ('Las Delicias', 'Las Delicias'), ('Fisherton', 'Fisherton'), ('Arroyito', 'Arroyito'), ('Pichincha', 'Pichincha'), ('Zona Norte', 'Zona Norte'), ('Zona Oeste', 'Zona Oeste'), ('zona_este', 'Zona Este'), ('Zona Sur', 'Zona Sur'), ('zona_suroeste', 'Zona Suroeste'), ('zona_sudeste', 'Zona Sudeste'), ('villa_gobernador_galvez', 'Villa Gobernador Gálvez'), ('granadero_baigorria', 'Granadero Baigorria'), ('ricardone', 'Ricardone'), ('san_lorenzo', 'San Lorenzo'), ('fray_luis_beltran', 'Fray Luis Beltrán'), ('funes', 'Funes'), ('roldan', 'Roldán'), ('soldini', 'Soldini'), ('perez', 'Pérez'), ('other', 'Otro')], max_length=50, null=True),
        ),
    ]
