# Generated by Django 5.1.5 on 2025-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0014_alter_departamentos_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='zona',
            field=models.CharField(blank=True, choices=[('Centro', 'Centro'), ('Macrocentro', 'Macrocentro'), ('Echesortu', 'Echesortu'), ('Abasto', 'Abasto'), ('Tablada', 'Tablada'), ('Las Delicias', 'Las Delicias'), ('Fisherton', 'Fisherton'), ('Arroyito', 'Arroyito'), ('Pichincha', 'Pichincha'), ('Zona Norte', 'Zona Norte'), ('Zona Oeste', 'Zona Oeste'), ('Zona Este', 'Zona Este'), ('Zona Sur', 'Zona Sur'), ('Zona Suroeste', 'Zona Suroeste'), ('Zona Sudeste', 'Zona Sudeste'), ('Villa Gobernador Gálvez', 'Villa Gobernador Gálvez'), ('Granadero Baigorria', 'Granadero Baigorria'), ('Ricardone', 'Ricardone'), ('San Lorenzo', 'San Lorenzo'), ('Fray Luis Beltrán', 'Fray Luis Beltrán'), ('Funes', 'Funes'), ('Roldan', 'Roldán'), ('Soldini', 'Soldini'), ('Perez', 'Pérez'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
    ]
