# Generated by Django 5.1.5 on 2025-11-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0016_alter_departamentos_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
