# Generated by Django 5.1.5 on 2025-11-16 18:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0021_alter_departamentos_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='imagendepartamento',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
